use Uber ;
#1. Retrieve all successful bookings:

 create view  all_bookings as 
 select * from bookings;
select * from all_bookings;

#2. Find the average ride distance for each vehicle type:
create view avg_ride_distance_for_each_vehicle as 
select vehicle_type, round(avg(Ride_Distance),2) as avg_ride_distance 
from bookings
group by vehicle_type;

select * from avg_ride_distance_for_each_vehicle;


#3. Get the total number of cancelled rides by customers:
create view total_ride_cancelled_by_customer as 
select count(*) as total_raid_cancelled_by_customer from bookings
 where Reason_for_Cancelling_by_Customer not like 'Not Applicable';
 
 select * from total_ride_cancelled_by_customer;
 

#4. List the top 5 customers who booked the highest number of rides:
create view  top5_customer as
 select customer_id, count(booking_id) as total_booking from bookings group by customer_id
order by total_booking desc limit 5;

select * from top5_customer;

#5. Get the number of rides cancelled by drivers due to personal and car-related issues:
create view ride_cancelled_for_personal_and_car_issue as 
select  driver_cancellation_reason ,count(*) as total_raid_cancelled from bookings
 where driver_cancellation_reason like 'Personal & Car related issues';
 
 select * from ride_cancelled_for_personal_and_car_issue;

#6. Find the maximum and minimum driver ratings for Prime Sedan bookings:
create view max_min_rating_for_prime_sedan as 
select max(driver_ratings) as 'Max Rating', min(driver_ratings) as 'Min Rating' from bookings
where vehicle_type = 'Premier Sedan';

select * from max_min_rating_for_prime_sedan;


#7. Retrieve all rides where payment was made using UPI:
create view total_upi_payment as 
SELECT payment_method, count(Payment_Method) 
 from bookings where payment_method='UPI';
 
 select * from total_upi_payment;

#8. Find the average customer rating per vehicle type:
create view avg_rating_for_each_vehicle_type as
select vehicle_type,round(avg(customer_rating),2) as avg_customer_ratings from bookings 
group by vehicle_type;

select * from avg_rating_for_each_vehicle_type;

#9. Calculate the total booking value of rides completed successfully by vehicle type:
create view total_revenue_by_vehicle_type as 
select vehicle_type,round(sum(booking_value)) total_revenue from bookings
 where booking_status = 'success'
 group by vehicle_type
 order by total_revenue desc;
 
 select * from total_revenue_by_vehicle_type;
 
 

#10. Total Count of incomplete rides reasons:
create view total_incomplete_ride_by_reason as 
select Incomplete_Rides_Reason,count(Incomplete_Rides_Reason) as 'Incomplete Raid Reason' from bookings
 where booking_status = 'incomplete'
 group by Incomplete_Rides_Reason ;
 
 select * from total_incomplete_ride_by_reason;
 
 #11. Find the total revenue generated by each payment method.
 create view total_revenue_by_payment_method as 
 select PAYMENT_METHOD,round(sum(booking_value)) as total_value from bookings 
 group by payment_method order by payment_method desc;
 
 select * from total_revenue_by_payment_method;
 
#12. Retrieve the top 3 vehicle types with the highest average booking value.
create view top3_vehicle_by_avg_booking_value as 
SELECT VEHICLE_TYPE,ROUND(avg(BOOKING_VALUE)) AS AVG_BOOKING_VALUE FROM BOOKINGS 
GROUP BY VEHICLE_TYPE ORDER BY AVG_BOOKING_VALUE DESC LIMIT 3;

select * from top3_vehicle_by_avg_booking_value;

#13. Count how many rides were completed per day.
create view total_ride_per_day as 
SELECT DATE,COUNT(*) AS TOTAL_RAIDS_COMPLETED FROM BOOKINGS WHERE BOOKING_STATUS='SUCCESS' 
GROUP BY DATE ORDER BY TOTAL_RAIDS_COMPLETED DESC;

select * from total_ride_per_day;

#14. Find the customer who has spent the most money overall on bookings.
create view top_customer as 
SELECT CUSTOMER_ID,ROUND(SUM(BOOKING_VALUE)) AS TOTAL_VALUE
 FROM BOOKINGS 
GROUP BY CUSTOMER_ID 
ORDER BY TOTAL_VALUE DESC LIMIT 3;

select * from top_customer;

#15. Display the average VTAT and CTAT for completed bookings only.
create view avg_vtat_ctat_for_completed_rides as
 SELECT ROUND(AVG(AVG_VTAT),2), ROUND(AVG(AVG_CTAT),2) FROM BOOKINGS WHERE BOOKING_STATUS='SUCCESS';

select * from avg_vtat_ctat_for_completed_rides;

#16. Retrieve all bookings that have a driver rating below 3.
create view rating_below_3_drivers as 
SELECT BOOKING_ID,DRIVER_RATINGS FROM BOOKINGS 
WHERE DRIVER_RATINGS < 3;

select * from rating_below_3_drivers;

#17. Count the total number of rides where the customer rating is greater than 4.
create view total_ride_with_4Star_rating_by_customer as 
SELECT COUNT(BOOKING_ID) FROM BOOKINGS WHERE CUSTOMER_RATING >4;

select * from total_ride_with_4Star_rating_by_customer;


#18. Retrieve the date with the highest number of bookings.
create view date_with_most_bookings as 
select date, count(booking_id) as total_booking from bookings 
group by date order by total_booking desc limit 3; 

select * from date_with_most_bookings;

#19. Display the total number of rides handled by each vehicle type in each payment method.
create view total_rides_by_each_vehicle_type_and_payment_method as 
select vehicle_type,payment_method,count(booking_id) as total_raid from bookings
group by vehicle_type, payment_method;

select * from total_rides_by_each_vehicle_type_and_payment_method;

#20. Retrieve the top 5 pickup locations that have the highest number of bookings.
create view hotspot_location as 
select pickup_location, count(pickup_location) as total_raid_from_location 
from bookings group by pickup_location order by total_raid_from_location desc limit 5;

select * from hotspot_location;

#21. Find how many rides were cancelled by drivers due to More than permitted people in there issues.
create view cancelled_by_driver_due_to_more_people_than_permitted as 
select count(*) as Total_Raid_Canceled from bookings 
where reason_for_cancelling_by_driver = 'More than permitted people in there';

select * from cancelled_by_driver_due_to_more_people_than_permitted;

# 22. driver's_total_ride_cancellation_by_reason
create view drivers_total_ride_cancellation_by_reason as
select reason_for_cancelling_by_driver,count(*) as Total_Raid_Canceled from bookings 
WHERE reason_for_cancelling_by_driver NOT LIKE 'Not Applicable'
GROUP BY reason_for_cancelling_by_driver ORDER BY TOTAL_RAID_CANCELED ;

select * from drivers_total_ride_cancellation_by_reason;

#23. Get the count of bookings made for each hour of the day (based on the Time column).
create view peak_hours_by_bookings as 
select hour(time) as booking_hours, count(time) as total_raids 
from bookings group by booking_hours order by booking_hours ;

select * from peak_hours_by_bookings;

#24. Calculate total booking value lost due to customer cancellations.
create view total_loss_due_to_customer_cancellation as 
select round(sum(booking_value)) as total_loss from bookings 
where reason_for_cancelling_by_customer not like 'not applicable';

select * from total_loss_due_to_customer_cancellation;

#25. Retrieve the month with the maximum total booking value.
create view month_with_max_Booking_value as 
select CONCAT(MONTHNAME(STR_TO_DATE(date, '%e/%c/%y')), ' ',
 YEAR(STR_TO_DATE(date, '%e/%c/%y'))) AS month,
 round(sum(booking_value)) as total_revenue from bookings 
group by monthname(date) order by total_revenue desc;

select * from month_with_max_Booking_value;


#26. Show the top 3 reasons for incomplete rides.
create view  top3_reason_for_incomplete_rides as 
select incomplete_rides_Reason, count(booking_id) as total_count from bookings
 where incomplete_rides_Reason not like 'Not Applicable'
 group by incomplete_rides_Reason 
 order by total_count desc limit 3;
 
 select * from top3_reason_for_incomplete_rides;
 
#27. Find the vehicle type that generated the highest total revenue.
create view vehicle_type_with_highest_total_revenue as 
select vehicle_type, round(sum(booking_value),2) as total_revenue 
from bookings group by vehicle_type order by total_revenue desc limit 1;

select * from vehicle_type_with_highest_total_revenue;

select sum(booking_value) as total_revenue from bookings;

#28. Calculate the total number of rides completed via cash payments.
create view total_rides_completed_via_cash_payment as 
select count(booking_id) as total_raid from bookings where payment_method='cash';

select * from total_rides_completed_via_cash_payment;

#29. Retrieve the highest,average and lowest booking values for each vehicle type.
create view highest_average_lowest_booking_value_vehicle_type as 
SELECT VEHICLE_TYPE,
ROUND(MIN(BOOKING_VALUE)) AS MINIMUM_VALUE,
ROUND(AVG(BOOKING_VALUE)) AS AVERAGE_BOOKING_VALUE,
ROUND(MAX(BOOKING_VALUE)) AS MAXIMUM_BOOKING_VALUE
FROM BOOKINGS GROUP BY VEHICLE_TYPE;

select * from highest_average_lowest_booking_value_vehicle_type;

# 30. Identify high-value bookings and tag them
create view total_rides_by_value_category as 
select count(*) as total_raid_by_value_category,
 case 
 when booking_value >= 1000 then 'High Value'
 when booking_value between 500 and 999 then 'Medium Value'
 else 'Low Value'
 end  as Category from bookings group by Category;
 
 select * from total_rides_by_value_category;
 
 #30. Calculate driver performance category
 create view drivers_performance_category as 
 select driver_ratings, 
 case when driver_ratings> 4.5 then 'excellent'
 when driver_ratings between 3.5 and 4.4 then 'good'
 when driver_ratings between 3.0 and 3.4 then 'average'
 else 'poor' 
 end as driver_performance_category,
 count(*) as total_rides
 from bookings 
 where booking_status = 'success'
 group by driver_performance_category, driver_ratings
 order by driver_ratings desc;
 
 select * from drivers_performance_category;
 
 select driver_ratings,
 case 
 when driver_ratings between 4.9 and  5 then 'Elite Driver'
 when driver_ratings  between 4.7 and 4.8 then 'Excellent Driver'
when driver_ratings between 4.4 and 4.6 then 'Reliable Driver'
when driver_Ratings between 4.0 and 4.3 then 'Average Driver'
when driver_ratings between 3.5 and 3.9 then 'Below Average Driver'
else 'Poor Driver'
end as Driver_category , count(*) as count from bookings group by Driver_category;


